### ISSUE TITLE
Step 0: Run R code locally on your own machine

### ISSUE THREAD

**Issue by apeltzer** [SMLMS/nfml#10]
### Description of feature

Run the R code in https://github.com/SMLMS/ml-pipeline once on your local machine just to familiarize yourself with how to get this to run.

**Comment by lurialeslie** [comment]
I am getting this error in line 14 of the ml_base.R code.
> source(config$ml.cv$grid.library)
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file './ml_grids.R': No such file or directory

I understand that it is related to the name of the file but I am unable to understand how to decode (config$ml.cv$grid.library) to put the right full path to the grids file
