### ISSUE TITLE
Step 2: Familiarize yourself with the dependencies of the R Scripts

### ISSUE THREAD

**Issue by apeltzer** [SMLMS/nfml#9]
### Description of feature

We should make a list of dependencies for the R code that is built into the current R Scripts, e.g. "tidyverse" + ?

Once we have that list, we can investigate what we need to make the code reproducible and use containers for the dependencies.

**Comment by apeltzer** [comment]
The current R code is here: https://github.com/SMLMS/ml-pipeline

**Comment by lurialeslie** [comment]
R base packages
- stats
- graphics
- gr Devices utils
- datasets
- methods
Other packages
- caret
- data.table
- dplyr
- lattice
- ggplot
- numpy
- pandas
- plyr
- pls
